# Trading strategy to be optimized
strategy:
  # Choose a strategy by using the name of the your strategy class/file
  name: NeuralNetwork
  
  # Mutation constraints on parameters
  constraints:
    # Format:
    # PARAMETER_NAME OPERATOR VALUE (separated by spaces)
    - w_i1_h1 > 0
    - w_i1_h1 < 10
    - w_il_h2 > -3


# Stock data that will be used for backtesting
stock_data:
  # List of data sets
  # NOTE: If you choose to use multiple datasets, the first one will be used for the final plot
  - ticker: SPY 
    start_date: 2007-12-01 # YYYY-MM-DD
    end_date: 2012-01-30 # YYYY-MM-DD
    weight: 0.6 # (float)


trading:
  # Amount of starting cash for each backtest
  starting_cash: 100000

  # Amount of commission for each trade
  commission: 0.0


# Parameters of the genetic optimization algorithm
genetic_algo_parameters:
  # Number of generations executed for optimization
  generation_count: 3

  # Number of parameter sets in each generation
  population: 10

  # Number of parameter sets to select from each generation
  selected: 4

  # Base standard deviation used for mutations
  bast_std: 0.1

  # Whether mutations are scaled based on the parameter's magnitude
  relative_std: False

  # Probability of a crossover occurring between two parents
  crossover_rate: 0.6

  # Seed used for generating random values (use "None" to generate seed)
  seed: None


saving_options:
  # Whether to use best parameters from previous run (true) or default parameters (false) for the initial population
  load_params: True

  # Whether to save the best parameters from the run
  save_params: False


print_options:
  # Maximum items outputted for each parameter set printed
  max_list: 5

  # true: outputs progress at each generation, false: outputs total progress
  detailed_progress: True